language: nix

env:
  global:
    # Install Racket where sudo not required.
    - RACKET_DIR="$HOME/racket"
  matrix:
    ##################################################################
    # To keep the matrix from growing too big/slow, test older Emacs #
    # only against very new Rackets. (Hopefully any problems with    #
    # older Rackets will be discovered elsewhere in the matrix when  #
    # testing with newer Emacs.)                                     #
    ##################################################################
    # Emacs 25.1
    - EMACS_CI=emacs-25-1 RACKET_VERSION=7.6
    - EMACS_CI=emacs-25-1 RACKET_VERSION=7.6 RACKET_CS=1
    - EMACS_CI=emacs-25-1 RACKET_VERSION=HEAD
    - EMACS_CI=emacs-25-1 RACKET_VERSION=HEADCS
    # Emacs 26.1
    - EMACS_CI=emacs-26-1 RACKET_VERSION=6.5
    - EMACS_CI=emacs-26-1 RACKET_VERSION=6.6
    - EMACS_CI=emacs-26-1 RACKET_VERSION=6.7
    - EMACS_CI=emacs-26-1 RACKET_VERSION=6.8
    - EMACS_CI=emacs-26-1 RACKET_VERSION=6.9
    - EMACS_CI=emacs-26-1 RACKET_VERSION=6.10
    - EMACS_CI=emacs-26-1 RACKET_VERSION=6.11
    - EMACS_CI=emacs-26-1 RACKET_VERSION=6.12
    - EMACS_CI=emacs-26-1 RACKET_VERSION=7.0
    - EMACS_CI=emacs-26-1 RACKET_VERSION=7.1
    - EMACS_CI=emacs-26-1 RACKET_VERSION=7.2
    - EMACS_CI=emacs-26-1 RACKET_VERSION=7.3
    - EMACS_CI=emacs-26-1 RACKET_VERSION=7.4
    - EMACS_CI=emacs-26-1 RACKET_VERSION=7.5
    - EMACS_CI=emacs-26-1 RACKET_VERSION=7.6
    - EMACS_CI=emacs-26-1 RACKET_VERSION=7.6 RACKET_CS=1
    - EMACS_CI=emacs-26-1 RACKET_VERSION=HEAD
    - EMACS_CI=emacs-26-1 RACKET_VERSION=HEADCS
    # Emacs snapshot. Because slow to make, test against only some key
    # versions of Racket like latest stable and HEAD. Also list these
    # jobs below under `allow_failures`, and use `fast_finish`.
    - EMACS_CI=emacs-snapshot RACKET_VERSION=7.6
    - EMACS_CI=emacs-snapshot RACKET_VERSION=HEAD

matrix:
  allow_failures:
    # bleeding edge Racket
    - env: EMACS_CI=emacs-25-1 RACKET_VERSION=HEAD
    - env: EMACS_CI=emacs-25-1 RACKET_VERSION=HEADCS
    - env: EMACS_CI=emacs-26-1 RACKET_VERSION=HEAD
    - env: EMACS_CI=emacs-26-1 RACKET_VERSION=HEADCS
    # bleeding edge Emacs
    - env: EMACS_CI=emacs-snapshot RACKET_VERSION=7.6
    - env: EMACS_CI=emacs-snapshot RACKET_VERSION=HEAD
  fast_finish: true

install:
  ## Emacs
  - bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)

  ## Racket
  - bash <(curl https://raw.githubusercontent.com/greghendershott/travis-racket/master/install-racket.sh)
  - export PATH="${RACKET_DIR}/bin:${PATH}" #install-racket.sh can't set for us

script:
  - make deps
  - make compile
  - make test
